name: trainer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get_it: ^5.0.6
  charts_flutter: ^0.9.0
  shared_preferences: 0.5.12+4
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.0.0
  test: 1.14.0


flutter:
  uses-material-design: true